[global]
address = "0.0.0.0"
environment = "development"

[development.server]
port = 8000

[staging.server]
port = 8000

[production.server]
port = 8000

[app_configs]
db = "postgres://root:password@localhost:5432/horde"
