[global]
address = "0.0.0.0"
environment = "development"

[development.server]
port = 8000

[staging.server]
port = 8000

[production.server]
port = 8000

[app]
db = "postgres://root:password@localhost:5432/horde"
api = "6af73b25-2432-4b79-af86-e7a14da8debc"
