---
- hosts: aws_servers
  become: yes
  tasks:
    - name: Installs nginx web server
      apt: pkg=nginx state=installed update_cache=true
      notify:
        - start nginx

    - file: path=/usr/share/nginx/html/index.html state=absent

    - name: Upload default index.html for host
      copy: src=./index.html dest=/usr/share/nginx/html/ mode=0755

  handlers:
    - name: start nginx
      service: name=nginx state=started
